### ISSUE TITLE
error parsing command output

### ISSUE THREAD

**Issue by moumita-das-7019** [monitoringartist/ZenPacks.JanGaraj.ZabbixAgent#1]
I am getting this error in zenoss console after installing this zenpack for my devices.

My device is ubuntu 18.04 with zabbix agent installed
My zenoss core is CentOS 6 , Zenoss 4.2.5.

ZenPacks.JanGaraj.ZabbixAgent 0.7.0 is installed.

I have used ZabbixAppZabbixAgent and ZabbixOSLinux templates with freshly created /Server/Zabbix  device class.

Event Details...
--
exceptionNo JSON object could be decodedmanagercent6-zenoss.us-central1-a.c.month-infra.internalstderr/bin/sh: /opt/zenoss/ZenPacks/ZenPacks.JanGaraj.ZabbixAgent-0.7.0.egg/ZenPacks/JanGaraj/ZabbixAgent/libexec/zabbix_get_zenoss: Permission denied /bin/sh: line 0: exec: /opt/zenoss/ZenPacks/ZenPacks.JanGaraj.ZabbixAgent-0.7.0.egg/ZenPacks/JanGaraj/ZabbixAgent/libexec/zabbix_get_zenoss: cannot execute: Permission denied | exception | No JSON object could be decoded | manager | cent6-zenoss.us-central1-a.c.month-infra.internal | stderr | /bin/sh: /opt/zenoss/ZenPacks/ZenPacks.JanGaraj.ZabbixAgent-0.7.0.egg/ZenPacks/JanGaraj/ZabbixAgent/libexec/zabbix_get_zenoss: Permission denied /bin/sh: line 0: exec: /opt/zenoss/ZenPacks/ZenPacks.JanGaraj.ZabbixAgent-0.7.0.egg/ZenPacks/JanGaraj/ZabbixAgent/libexec/zabbix_get_zenoss: cannot execute: Permission denied
exception | No JSON object could be decoded

stderr | /bin/sh: /opt/zenoss/ZenPacks/ZenPacks.JanGaraj.ZabbixAgent-0.7.0.egg/ZenPacks/JanGaraj/ZabbixAgent/libexec/zabbix_get_zenoss: Permission denied /bin/sh: line 0: exec: /opt/zenoss/ZenPacks/ZenPacks.JanGaraj.ZabbixAgent-0.7.0.egg/ZenPacks/JanGaraj/ZabbixAgent/libexec/zabbix_get_zenoss: cannot execute: Permission denied

--

**Comment by jangaraj** [comment]
> /opt/zenoss/ZenPacks/ZenPacks.JanGaraj.ZabbixAgent-0.7.0.egg/ZenPacks/JanGaraj/ZabbixAgent/libexec/zabbix_get_zenoss
> cannot execute: Permission denied

There is no permission to execute that file, so just try:
```
chmod +x /opt/zenoss/ZenPacks/ZenPacks.JanGaraj.ZabbixAgent-0.7.0.egg/ZenPacks/JanGaraj/ZabbixAgent/libexec/zabbix_get_zenoss
```

**Comment by moumita-das-7019** [comment]
It helps ! Thank you so much!!
