### ISSUE TITLE
Zabbix Agent Zenpack is being applied to all nodes 

### ISSUE THREAD

**Issue by moumita-das-7019** [monitoringartist/ZenPacks.JanGaraj.ZabbixAgent#2]
I have created Device class Server/Zabbix where I have bound zabbix templates for Linux OS , but I am getting agent not found error for other servers which are in Server/Linux Device class. For example, this is the templates for this device:
![image](https://user-images.githubusercontent.com/56260090/82202294-53f7b500-991f-11ea-8ab2-b9f8b85a6470.png)

modular pluggings
![image](https://user-images.githubusercontent.com/56260090/82202398-78ec2800-991f-11ea-8baa-9647bc801f66.png)

Still alert for zabbix agent in non zabbix node:
![image](https://user-images.githubusercontent.com/56260090/82202506-a3d67c00-991f-11ea-8457-579ec03355c7.png)

**Comment by jangaraj** [comment]
It isn't a zenpack issue but your infrastructure network connectivity issue, so it isn't in the scope of this repo. 

`Connection refused`: it can be firewall, it can be zabbix agent configuration (check&configure Server/ServerActive config options), ...

**Comment by moumita-das-7019** [comment]
It's not for connection issue of firewall. See the node here I mentioned is
not having zabbix agent , and it is well monitored by zenoss. But this
alert is for not being able to connect zabbix agent on specific port(
because the server don't have zabbix agent). And I tested with other nodes,
any new node I m adding without zabbix agent is resulting in this error.
